Bearer/bearer-rules

javascript/aws_lambda/sql_injection.yml, javascript/aws_lambda/sql_injection/.snapshots/mysql2_sql_injection.yml, javascript/express/insecure_allow_origin.yml, javascript/express/insecure_allow_origin/.snapshots/insecure_allow_origin.yml, javascript/express/sql_injection.yml, javascript/express/sql_injection/.snapshots/knex_sql_injection.yml, javascript/lang/jwt_hardcoded_secret.yml, javascript/lang/jwt_hardcoded_secret/.snapshots/unsecure_jose_jwt.yml, javascript/lang/jwt_hardcoded_secret/testdata/secure.js, javascript/lang/jwt_hardcoded_secret/testdata/unsecure_jose_jwt.js
Makes the following fixes to Javascript rules:
- `javascript_aws_lambda_sql_injection` and `javascript_express_insecure_allow_origin` - use local aux rules (were accidentally referencing other rules)
- `javascript_express_sql_injection` - Support chained knex calls
- `javascript_lang_jwt_hardcoded_secret` - Fix Jose rule
- Close https://github.com/Bearer/bearer-rules/issues/20
- Close https://github.com/Bearer/bearer/issues/884
- Close https://github.com/Bearer/bearer/issues/883
=> fix: rule bugfixes

scripts/run_tests.sh
Currently we are using a pre-release move to using latest stable. Do not merge till this branch is passing CI ie new version supporting external rules is released
=> ci: update to use latest image

javascript/express/insecure_allow_origin.yml, javascript/express/insecure_allow_origin/.snapshots/insecure_allow_origin_query.yml, javascript/express/insecure_allow_origin/testdata/insecure_allow_origin_query.js, scripts/run_tests.sh
=> feat(express): improve insecure allow origin rule

.github/workflows/integration_tests.yml
Change the integration tests workflow to cancel previous jobs on the same branch.
Currently if you push additional changes when the tests are running, we tie up resources continuing to run the tests against the old commit.
=> ci: cancel previous tests on the same branch

javascript/express/hardcoded_secret.yml, javascript/express/jwt_not_revoked.yml, javascript/express/jwt_not_revoked/.snapshots/express_jwt_not_revoked.yml, javascript/express/jwt_not_revoked/testdata/express_jwt_not_revoked.js
Match on juice-shop examples, which use `expressJwt` instead of `expressjwt`
Relates to #49
=> fix: case sensitivity in JWT JS rules

javascript/lang/raw_html_using_user_input.yml, javascript/lang/raw_html_using_user_input/.snapshots/bad.yml, javascript/lang/raw_html_using_user_input/testdata/bad.js, javascript/lang/raw_html_using_user_input/testdata/ok.js
Adds support for detecting template strings (calls to libraries that render templates) containing user input to the Javascript raw HTML rule.
=> feat: add template libaries to javascript raw html rule

ruby/lang/reflection_using_user_input.yml, ruby/lang/reflection_using_user_input/.snapshots/unsafe_rails.yml, ruby/lang/reflection_using_user_input/testdata/unsafe_rails.rb
Add `try` method to ruby reflection using user input rule. The `try` method is similar to e.g. `public_send` and calling it with untrusted input poses a security risk
=> feat: add try method to ruby reflection rule

javascript/third_parties/dom_purify.yml, javascript/third_parties/dom_purify/.snapshots/unsecure.yml, javascript/third_parties/dom_purify/testdata/secure.js, javascript/third_parties/dom_purify/testdata/unsecure.js
Extends existing rule to catch cases where no config is set when using `DOMpurify.sanitize`
=> fix: add no config case to DOMpurify JS rule

.github/workflows/canary.yml
Adds a new Canary Github workflow that creates a draft release. This will allow us to debug the packaging/release artifacts.
=> ci: add canary release workflow

.github/workflows/canary.yml, .github/workflows/release.yml
We don't have any shared Java rules yet so trying to package them causes an error.
We'll have to remember to add this back when we create the first shared rule.
=> ci: don't package shared java rules

ruby/rails/unsafe_mass_assignment.yml, ruby/rails/unsafe_mass_assignment/.snapshots/unsafe.yml
Set severity level for new Rails mass assignment rule to `warning`
Oversight from https://github.com/Bearer/bearer-rules/pull/67
=> fix: set severity to warning

ruby/rails/sql_injection.yml, ruby/rails/sql_injection/testdata/ok_using_bind.rb
We're now catching cases like the following again
```
search_params = {
name: params[:name],
organization_id: params[:organization_id]
}
Project.find_by(search_params)
```
=> fix: fix Rails SQL injection pattern

.github/workflows/canary_integration_tests.yml
Split out canary testing and move it to a manual process.
PR's do not need to be working on next version as well as current.
=> ci: split out canary test and make it manual

.github/workflows/canary.yml, .github/workflows/release.yml
Make sure we include shared Java rules dir in rules release
=> fix: include shared java rules dir

java/lang/file_permission_others.yml, java/lang/missing_integrity_check.yml, java/lang/padding_oracle_encryption_vulnerability.yml, java/lang/path_traversal.yml, java/lang/rsa_no_padding.yml, java/shared/lang/cipher_des_init.yml, java/shared/lang/message_digest_md5_init.yml
Clean up Java type import regex patterns following https://github.com/Bearer/bearer-rules/pull/108#discussion_r1230999583
=> fix: clean Java regex patterns

java/lang/ldap_injection.yml, java/lang/ldap_injection/.snapshots/ldap_injection.yml, java/lang/ldap_injection/testdata/ldap_injection.java
Extend LDAP injection rule to include `lookup` and `list` methods
Relates to #44
=> feat(java): extend LDAP injection rule

java/lang/xss_response_writer.yml
Add additional encode method to sanitizer pattern for Java's XSS response writer rule
=> fix(java): add encode method for XSS response writer

.github/workflows/integration_tests.yml, java/lang/sqli.yml, java/lang/sqli/.snapshots/string_concatenation.yml, java/lang/sqli/testdata/safe.java, java/lang/sqli/testdata/string_concatenation.java, java/lang/xss_servlet_parameter/.snapshots/bad.yml, java/lang/xss_servlet_parameter/testdata/bad.java, java/shared/lang/instance.yml, java/spring/sqli.yml, java/spring/sqli/.snapshots/string_concatenation.yml, java/spring/sqli/testdata/safe.java, java/spring/sqli/testdata/string_concatenation.java
Makes the Java SQL injection rules stricter about the types they match. 
The patterns are currently quite generic (eg. `execute`) which causes a lot of false positives with non-database code.
- Closes #80
=> fix(java): make sql injection rule stricter

java/lang/file_permission_others.yml, java/lang/file_permission_others/.snapshots/others.yml
Remove requirement for `setPosixFilePermissions` from Java file permission rule pattern
We were missing nested cases of the `setPosixFilePermissions` call (similar issue to https://github.com/Bearer/bearer-rules/issues/122) but on reflection, with this rule, the bad part is adding the OTHERS permission rather than the `setPosixFilePermissions` call itself, so we simplify the rule pattern. 
Severity level remains at WARNING
=> fix(java): file permission others rule

java/lang/information_leakage.yml
Replace `ERROR` with `EXCEPTION` in rule pattern
=> fix(java): typo in information leak rule

ruby/lang/insecure_ftp.yml, ruby/lang/insecure_ftp/.snapshots/ftp_new.yml, ruby/lang/insecure_ftp/.snapshots/ftp_open.yml, ruby/lang/insecure_ftp/.snapshots/ftp_open_with_datatype.yml
current description for `ruby_lang_insecure_ftp` formats very badly update the markup a bit to make it more readable
=> docs: update description ruby_lang_insecure_ftp

java/lang/information_leakage.yml, java/lang/information_leakage/.snapshots/leak.yml, java/lang/information_leakage/testdata/ok.java, java/lang/trust_boundary_violation/.snapshots/bad.yml, java/lang/trust_boundary_violation/testdata/bad.java, java/shared/lang/instance.yml
Support exception handlers on resource blocks in Java shared instance rule, and use the shared rule in the information leakage rule.
- Close https://github.com/Bearer/bearer-rules/issues/122
=> feat(java): match more cases in info leakage rule

javascript/express/helmet_missing.yml, javascript/express/helmet_missing/.snapshots/insecure.yml, javascript/express/reduce_fingerprint.yml, javascript/express/reduce_fingerprint/.snapshots/insecure.yml
Fix duplicate titles for JS Express rules for Helmet and server fingerprinting security configurations. 
Both show up as `"LOW: Security misconfiguration detected. [CWE-693]"` in the report and this is pretty confusing.
=> docs: duplicate titles for JS Express rules

.github/workflows/canary.yml, .github/workflows/release.yml
Slight oversight in #143 meant that rules archives would be prefixed by a rules folder unlike previous versions this corrects that issue.
=> ci: scope release workflows to lang dir

rules/java/lang/insufficiently_random_values.yml, tests/java/lang/insufficiently_random_values/__snapshots__/test.js.snap, tests/java/lang/insufficiently_random_values/testdata/ok_secure_random.java
Since Java's `SecureRandom` is an instance of `Random`, our rule can have false positives in the example below
```java
public class Foo {
public void main() {
java.util.Random numGen = java.security.SecureRandom.getInstance("SHA1PRNG");
double rand = getNextNumber(numGen);
String key = Double.toString(rand).substring(2);
}
double getNextNumber(java.util.Random generator) {
return generator.nextDouble(); // <- this is fine when SecureRandom is passed to this function (as above)
}
}
```
A possible fix is to catch on instantiation (i.e. `Random.new`) instead of method calls. Open to other more sophisticated solutions. 
Closes [#115](https://github.com/Bearer/bearer-rules/issues/115)
=> fix: Java Random rule pattern

rules/javascript/react/dangerously_set_inner_html.yml, rules/javascript/shared/third_parties/sanitize_html_sanitizer.yml, tests/javascript/lang/dangerous_insert_html/testdata/secure.js, tests/javascript/react/dangerously_set_inner_html/__snapshots__/test.js.snap, tests/javascript/react/dangerously_set_inner_html/test.js, tests/javascript/react/dangerously_set_inner_html/testdata/secure-dom_purify.tsx
We were classifying React Inner HTML incorrectly when `DOMPurify` was used to sanitize the input
=> fix: improve sanitizer for react inner html

rules/javascript/express/jwt_not_revoked.yml, tests/javascript/express/jwt_not_revoked/__snapshots__/test.js.snap, tests/javascript/express/jwt_not_revoked/test.js, tests/javascript/express/jwt_not_revoked/testdata/insecurity.ts
We were not taking into account  `as_expression` so the scope needs to be `result` instead of `cursor`
=> fix: improve jwt not revoked rules and tests

rules/ruby/lang/path_using_user_input.yml, tests/ruby/lang/path_using_user_input/__snapshots__/test.js.snap
Update copy for Ruby lang `path_using_user_input` to bring it in line with other rule copy
=> fix: ruby lang rule title

rules/ruby/rails/password_length.yml, tests/ruby/rails/password_length/__snapshots__/test.js.snap, tests/ruby/rails/password_length/test.js, tests/ruby/rails/password_length/testdata/devise.rb
Improve line detection from Devise config file
=> feat(ruby): improve devise line matching

rules/javascript/shared/common/datatype.yml, rules/ruby/shared/common/datatype.yml
Removes an unwanted semicolon that was causing the shared Ruby datatype rule to fail in older CLI versions.
Also removes the semicolon from the Javascript rule - this has no functional effect but is done for consistency with not using semicolons in JS rules.
=> fix: remove unwanted semicolon in ruby datatype rule

.envrc.example, scripts/invoke.sh
Remove feature flags since it's about to be merged :)
Related https://github.com/Bearer/bearer/pull/1336
=> chore: remove feature flags for new languages

rules/javascript/shared/third_parties/sanitize_html_sanitizer.yml, tests/javascript/lang/raw_html_using_user_input/testdata/ok.js
Adds `sanitizer(...)` as a fallback for Javascript HTML user input.
=> fix(javascript): add fallback for html user input sanitizer

scripts/invoke.sh, tests/helper.js, tests/javascript/lang/eval_user_input/__snapshots__/test.js.snap, tests/javascript/lang/eval_user_input/test.js, tests/javascript/lang/eval_user_input/testdata/eval.js
Ref https://github.com/Bearer/bearer/issues/1405
Example of how the testing could be done following this https://github.com/Bearer/bearer/pull/1404
=> chore: add new evaluator

rules/go/gosec/blocklist/cgi.yml, rules/go/gosec/blocklist/des.yml, rules/go/gosec/blocklist/md5.yml, rules/go/gosec/blocklist/rc4.yml, rules/go/gosec/blocklist/sha1.yml, rules/go/gosec/leak/pprof_endpoint.yml, tests/go/gosec/blocklist/cgi/__snapshots__/test.js.snap, tests/go/gosec/blocklist/des/__snapshots__/test.js.snap, tests/go/gosec/blocklist/md5/__snapshots__/test.js.snap, tests/go/gosec/blocklist/rc4/__snapshots__/test.js.snap, tests/go/gosec/blocklist/sha1/__snapshots__/test.js.snap, tests/go/gosec/leak/pprof_endpoint/__snapshots__/test.js.snap
Set the focus on the encryption library.
That way, the correct library is being reported and we don't end up reporting an entire `import` block and end up reporting omitted lines with the vuln being in one of those omitted lines
=> fix(go): focus weak encryption library

rules/go/gosec/subproc/subproc.yml, tests/go/gosec/subproc/subproc/__snapshots__/test.js.snap, tests/go/gosec/subproc/subproc/testdata/main.go
Improve gosec subproc detections
=> fix: update subcommand

rules/go/gosec/sql/concat_sqli.yml, tests/go/gosec/sql/concat_sqli/__snapshots__/test.js.snap, tests/go/gosec/sql/concat_sqli/testdata/main.go
=> fix: improve gosec sqli

CONTRIBUTING.md
Use relative link - current link is a 404 because it is missing the tree
=> docs: fix broken link in contribution guide

scripts/write_v2_testfile.js
Add simple helper script to write a testdata and test.js files (and any folders, if not existing) for a new rule being added
Usage example
```bash
node scripts/write_v2_testfile.js "/Users/mish/Bearer/bearer-rules/rules/java/lang/logger.yml" 
```
will create the following testdata file: 
`/Users/mish/Bearer/bearer-rules/tests/java/lang/logger/main.java`
with the following content:
```
// Use bearer:expected <rule_name> to flag expected findings
```
and an associated test.js file with the following content: 
```
const {
createNewInvoker,
getEnvironment,
} = require("../../../helper.js")
const { ruleId, ruleFile, testBase } = getEnvironment(__dirname)
describe(ruleId, () => {
const invoke = createNewInvoker(ruleId, ruleFile, testBase)
test("logger", () => {
const testCase = "main.java" …
```
=> feat: add script to write test files for V2 tests

rules/java/lang/bad_hex_conversion.yml, rules/java/shared/lang/message_digest_any_init.yml, rules/java/shared/lang/message_digest_buffer.yml, tests/java/lang/bad_hex_conversion/test.js, tests/java/lang/bad_hex_conversion/testdata/main.java
Add Java lang rule for bad Hex conversions for digest buffers which can lead to inaccurate results. 
This rule has a default `warning` level severity
=> feat(java): add bad hex conversion rule

rules/java/lang/dangerous_permissions.yml, tests/java/lang/dangerous_permissions/test.js, tests/java/lang/dangerous_permissions/testdata/main.java
Add Java rule to catch the granting of dangerous permissions
=> feat(java): add dangerous permissions rule

rules/java/lang/weak_encryption_ecb_mode.yml, tests/java/lang/weak_encryption_ecb_mode/test.js, tests/java/lang/weak_encryption_ecb_mode/testdata/main.java
Add rule to guard against using ECB cipher mode
=> feat(java): add ECB cipher mode rule

rules/java/lang/custom_message_digest_class.yml, tests/java/lang/custom_message_digest_class/test.js, tests/java/lang/custom_message_digest_class/testdata/main.java
Add warning-level rule against implementing custom `MessageDigest` classes
=> feat(java): custom MessageDigest class

rules/java/lang/expression_language_injection.yml, tests/java/lang/expression_language_injection/test.js, tests/java/lang/expression_language_injection/testdata/main.java
Add Java rule to check for EL injection
=> feat(java): add EL injection rule

rules/java/lang/external_config_control.yml, tests/java/lang/external_config_control/test.js, tests/java/lang/external_config_control/testdata/main.java
Add external config CWE-15 rule for Java to catch SQL Connection setCatalog method calls with user supplied input
=> feat(java): add SQL external config rule

rules/java/lang/crlf_injection.yml, rules/java/lang/log_injection.yml, rules/java/lang/logger.yml, rules/java/shared/lang/logger_methods.yml, tests/java/lang/crlf_injection/test.js, tests/java/lang/crlf_injection/testdata/main.java, tests/java/lang/log_injection/test.js, tests/java/lang/log_injection/testdata/main.java
Add Java rule for Carriage Return, Line Feed injection attacks
Some refactoring of other logger rules, to remove shared functionality
=> feat(jave): add CRLF injection rule

rules/java/lang/file_upload_filename.yml, tests/java/lang/file_upload_filename/test.js, tests/java/lang/file_upload_filename/testdata/main.java
Add rule for path traversal with Java FileUpload filename
=> feat(java): add file upload filename rule

rules/java/lang/expression_language_injection.yml
Clean up unused shared method
Refactor variable names for clarify
=> fix(java): clean up EL injection rule

rules/java/lang/format_string_manipulation.yml, tests/java/lang/format_string_manipulation/test.js, tests/java/lang/format_string_manipulation/testdata/main.java
Add Java rule for format string injection
=> feat(java): format string manipulation rule

rules/java/lang/empty_database_password.yml, tests/java/lang/empty_database_password/test.js, tests/java/lang/empty_database_password/testdata/main.java
Add Java rule to catch databases configured with empty passwords
=> feat(java): empty database password rule

rules/java/lang/http_parameter_pollution.yml, tests/java/lang/http_parameter_pollution/test.js, tests/java/lang/http_parameter_pollution/testdata/main.java
Add Java rule for HTTP Param Pollution (HPP)
=> feat(java): HTTP Param Pollution

rules/java/lang/http_response_splitting.yml, rules/java/shared/lang/user_input.yml, tests/java/lang/http_response_splitting/test.js, tests/java/lang/http_response_splitting/testdata/main.java
* Add some more cases to the existing HTTP response splitting rule, as well as a new-style test for these
* Add missing method (`getPathInfo`) to Java's shared user input rule
=> feat(java): extend HTTP response splitting rule

rules/java/lang/hardcoded_secret.yml, tests/java/lang/hardcoded_secret/test.js, tests/java/lang/hardcoded_secret/testdata/main.java
Add hardcoded secret rule for Java lang. Here we follow the existing PHP rule and catch on non-trivial strings (and char arrays) assigned to suspect variable names like `PASSWORD` or `apiKey`. 
We do not check for usage as a leaked password in source code is bad practice, whether or not it is in use. 
=> feat(java): add hardcoded secret rule

rules/java/lang/cookie_missing_http_only.yml, rules/java/lang/cookie_missing_secure.yml, tests/java/lang/cookie_missing_http_only/test.js, tests/java/lang/cookie_missing_http_only/testdata/main.java, tests/java/lang/cookie_missing_secure/test.js, tests/java/lang/cookie_missing_secure/testdata/main.java
Add Jakarta case to Java insecure cookie rules
=> feat(java): extend insecure cookie rules

rules/java/lang/expression_language_injection.yml
Remove additional CWE for Java EL injection rule, leaving the correct CWE-917 Improper Neutralization of Special Elements used in an Expression Language Statement ('Expression Language Injection')
https://cwe.mitre.org/data/definitions/917.html
=> fix: multiple CWEs for Java EL injection rule

rules/java/lang/file_upload_filename.yml
Fix bad CWE for Java file upload filename rule - here we have unsanitized user input as a filename, which is CWE-73 (External Control of File Name or Path) and not CWE-22 (Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal'))
https://cwe.mitre.org/data/definitions/73.html
https://cwe.mitre.org/data/definitions/22.html
=> fix: incorrect CWE for Java file upload filename rule

rules/java/lang/code_injection_rule.yml, tests/java/lang/code_injection_rule/test.js, tests/java/lang/code_injection_rule/testdata/main.java
Add code injection rule for Java
=> feat(java): code injection rule (CWE-94)

rules/java/lang/insecure_allow_origin.yml, rules/java/shared/lang/user_input.yml, tests/java/lang/insecure_allow_origin/test.js, tests/java/lang/insecure_allow_origin/testdata/main.java
Add Java rule to check when Allow Origin contains raw user input
Also extend shared user input rule
=> feat(java): add insecure allow origin rule (CWE-942)

.github/workflows/canary_integration_tests.yml, .github/workflows/integration_tests.yml, rules/java/android/prevent_screenshot.yml, tests/java/android/prevent_screenshot/test.js, tests/java/android/prevent_screenshot/testdata/main.java
Add android folder (and update integration test scripts)
Add rule to prevent enabling of screenshots in Android applications
=> feat(java/android): add screenshot prevention rule (CWE-200)

rules/java/android/world_readable_writable_mode.yml, tests/java/android/world_readable_writable_mode/test.js, tests/java/android/world_readable_writable_mode/testdata/main.java
Add Android rule around MODE_WORLD_READABLE and MODE_WORLD_WRITEABLE
Note, these constants were deprecated since Android API level 17 and have now been removed but since it's quite a bad one, we add the rule for legacy applications
=> feat(java/android): add world readable/writeable rule (CWE-276)

rules/java/lang/missing_tls_validation.yml, tests/java/lang/ssl_verification/test.js, tests/java/lang/ssl_verification/testdata/main.java
Add initial rule for missing SSL verification
=> feat(java): missing TLS validation

rules/java/lang/socket_init.yml, tests/java/lang/socket_init/test.js, tests/java/lang/socket_init/testdata/main.java
Warning-level rule to discourage using Socket init (instead of a SSL Socket Factory) when creating SSL/TLS connections
=> feat(java): add warning-level rule about socket creation best practices (CWE-319)

rules/java/lang/deserialization_of_user_input.yml, tests/java/lang/deserialization_of_user_input/test.js, tests/java/lang/deserialization_of_user_input/testdata/main.java
Add Java rule for deserializing user input
=> feat(java): deserialization of user input (CWE-502)

rules/java/android/prevent_screenshot.yml
Clean up - imports is no longer used in this rule so we can remove it
=> fix: remove unused imports

rules/java/lang/insecure_allow_origin.yml
This rule is CWE-346 - lack of validating allowed origins - and not CWE-942 - overly permissive CORS policy e.g. `allowedOrigins("*")`
=> fix: cwe for Java insecure allow origin

rules/php/lang/permissive_allow_origin.yml, rules/php/symfony/permissive_allow_origin.yml, tests/php/lang/permissive_allow_origin/__snapshots__/test.js.snap, tests/php/symfony/permissive_allow_origin/__snapshots__/test.js.snap
Permissive CORS is CWE-942 https://cwe.mitre.org/data/definitions/942.html and not CWE-346 which is insecure origins (i.e. user-controlled)
=> fix: allow origin cwes for php rules

rules/java/lang/permissive_allow_origin.yml, tests/java/lang/permissive_allow_origin/test.js, tests/java/lang/permissive_allow_origin/testdata/main.java
Add Java rule to catch overly permissive CORS policy (Allow Origin Header set to *)
=> feat(java): add permissive allow origin rule (CWE-942)

rules/java/lang/eval_using_user_input.yml, tests/java/lang/eval_using_user_input/test.js, tests/java/lang/eval_using_user_input/testdata/main.java
Add eval injection rule for Java
=> feat(java): add eval injection rule (CWE-95)

rules/java/lang/regex_using_user_input.yml, tests/java/lang/regex_using_user_input/test.js, tests/java/lang/regex_using_user_input/testdata/main.java
Add Java rule to catch cases of `Pattern.compile` with user input (susceptible to ReDoS attacks)
=> feat(java): regex using user input (CWE-1287)

rules/java/lang/permissive_cookie_config.yml, tests/java/lang/permissive_cookie_config/test.js, tests/java/lang/permissive_cookie_config/testdata/main.java
Add rule to catch permissive cookie configuration
=> feat(java): permissive cookie config (CWE-693)

scripts/generate_rule.js
Naïve fix to script so we can generate third party rules (different file structure)
=> fix: quick solution to handle third parties repo

rules/php/shared/lang/user_input_sanitizer.yml, tests/php/lang/raw_html_using_user_input/testdata/ok.php, tests/php/lang/raw_output_using_user_input/testdata/echo.php
Casting to int is a common method to sanitize form variables so we should include it here
- #172
=> feat(php): improve input sanitizer

rules/php/lang/weak_hash_adler32.yml, rules/php/lang/weak_hash_crc32.yml, tests/php/lang/weak_hash_adler32/test.js, tests/php/lang/weak_hash_adler32/testdata/index.php, tests/php/lang/weak_hash_crc32/test.js, tests/php/lang/weak_hash_crc32/testdata/index.php
Add coverage for some of the more common weak hashing algos in PHP. 
- Close #217
=> feat(php): add coverage for crc32 and adler32

rules/java/third_parties/algolia.yml, tests/java/third_parties/algolia/test.js, tests/java/third_parties/algolia/testdata/main.java
Add Java third party rule for Algolia
=> feat(java): add third party rule for Algolia (CWE-201)

rules/java/lang/apache_commons_collection.yml, tests/java/lang/apache_commons_collection/test.js, tests/java/lang/apache_commons_collection/testdata/insecure/main.java, tests/java/lang/apache_commons_collection/testdata/insecure/maven-dependencies.json, tests/java/lang/apache_commons_collection/testdata/secure/main.java, tests/java/lang/apache_commons_collection/testdata/secure/maven-dependencies.json
Known vulnerability for InvokerTransformer class for commons collections 3 versions older than 3.2.2
https://commons.apache.org/proper/commons-collections/security-reports.html
=> feat(java): vulnerable Apache commons collection version (CWE-1395)

rules/php/lang/permissive_allow_origin.yml, tests/php/lang/permissive_allow_origin/__snapshots__/test.js.snap, tests/php/lang/permissive_allow_origin/testdata/bad.php, tests/php/lang/permissive_allow_origin/testdata/ok.php
Improve `php_lang_permissive_allow_origin` coverage
=> feat: improve allow origin matching

rules/java/third_parties/rollbar.yml, tests/java/third_parties/rollbar/test.js, tests/java/third_parties/rollbar/testdata/main.java
Add third party Java rule for Rollbar API
=> feat(java): third parties rollbar (CWE-201)

rules/java/third_parties/open_telemetry.yml, tests/java/third_parties/open_telemetry/test.js, tests/java/third_parties/open_telemetry/testdata/main.java
Add third party Java rule for Open Telemetry
=> feat(java): add third parties open telemetry

rules/java/third_parties/new_relic.yml, tests/java/third_parties/new_relic/test.js, tests/java/third_parties/new_relic/testdata/main.java
Add third party Java rule for New Relic data leakage
=> feat(java): third parties new relic

rules/go/lang/deserialization_of_user_input.yml, tests/go/lang/deserialization_of_user_input/test.js, tests/go/lang/deserialization_of_user_input/testdata/main.go
Add Golang deserialization of external input rule
Relates to #271
=> feat(go): deserialization of user input (CWE-502)

rules/go/lang/log_output_neutralization.yml, tests/go/lang/log_output_neutralization/test.js, tests/go/lang/log_output_neutralization/testdata/main.go
Add Go rule to catch cases of missing log output neutralization. 
Relates to #271 
This rule is similar to CWE-93 (CRLF injection) so if/when we add this rule for Golang there may be some overlap.
=> feat(go): add log output neutralization (CWE-117)

rules/go/lang/insufficiently_random_values.yml, tests/go/lang/insufficiently_random_values/test.js, tests/go/lang/insufficiently_random_values/testdata/main.go
Add CWE 330
Related to https://github.com/Bearer/bearer-rules/issues/271
=> feat(golang): add cwe 330

rules/go/lang/permissive_regex_validation.yml, tests/go/lang/permissive_regex_validation/test.js, tests/go/lang/permissive_regex_validation/testdata/main.go
Add golang rule to catch regular expressions missing boundaries
Relates to #271
=> feat(go): permissive regexp (CWE-625)

rules/javascript/lang/unsafe_deserialization.yml, tests/javascript/lang/unsafe_deserialization/test.js, tests/javascript/lang/unsafe_deserialization/testdata/app.js
Add deserialization rule around YAML parsing for JS lang
=> feat(js): add deserialization rule

.github/workflows/canary_integration_tests.yml, .github/workflows/integration_tests.yml, rules/javascript/hapi/open_redirect.yml, rules/javascript/shared/express/user_input.yml, tests/javascript/express/open_redirect/test.js, tests/javascript/express/open_redirect/testdata/app.ts, tests/javascript/hapi/open_redirect/test.js, tests/javascript/hapi/open_redirect/testdata/app.js, tests/javascript/hapi/open_redirect/testdata/app.ts
Extend express open redirect rule
Add hapi as a new framework folder
Add hapi open redirect rule
=> fix(js): extend and add open redirect rules

rules/javascript/express/open_redirect.yml, rules/javascript/hapi/open_redirect.yml, rules/javascript/shared/express/user_input.yml, tests/javascript/hapi/open_redirect/testdata/app.ts
* Naïve prevention of duplicates between hapi and express open redirect rules
* Add `request` fallback to user input
=> fix: open redirect js rules

rules/javascript/lang/non_literal_fs_filename.yml, tests/javascript/lang/non_literal_fs_filename/test.js, tests/javascript/lang/non_literal_fs_filename/testdata/app.js
Add warning-level rule to catch external input (dynamic data, function args) used in fs function calls
=> feat(js): add external input in filename

.github/workflows/canary_integration_tests.yml, .github/workflows/integration_tests.yml, rules/javascript/node/missing_tls_validation.yml, tests/javascript/node/missing_tls_validation/test.js, tests/javascript/node/missing_tls_validation/testdata/app.js
Add javascript/node folder
Add rule for disabled TLS verification
=> feat(js): add missing TLS rule for Node

rules/javascript/lang/handlebars_no_escape.yml, tests/javascript/lang/handlebars_no_escape/test.js, tests/javascript/lang/handlebars_no_escape/testdata/app.js
Add Handlebars templating rule to catch cases of noEscape: true which could lead to XSS attacks
=> feat(js): add handlebars XSS rule

rules/java/lang/ssl_hostname_verifier.yml, tests/java/lang/ssl_hostname_verifier/test.js, tests/java/lang/ssl_hostname_verifier/testdata/main.java
Add java rule for missing / permissive SSL hostname verification
=> feat(java): missing or permissive ssl hostname verifier (CWE-295)

rules/java/lang/hardcoded_secret.yml, tests/java/lang/hardcoded_secret/testdata/main.java
Extend hardcoded secret rule to include the following 3 cases
* String collections (e.g. `String[] SECRETS = { "hello", "world" }`)
* Base64 encoded JWT tokens - such weak encoding is arguable plaintext
* Equality tests against hardcoded password strings
=> feat(java): extend hardcoded secret rule

rules/javascript/lang/observable_timing.yml
CWE-208 for timing attacks, not CWE-409 Improper Handling of Highly Compressed Data (Data Amplification)
=> fix(js): incorrect CWE for observable timing rule

rules/java/lang/xml_external_entity_vulnerability.yml, tests/java/lang/xml_external_entity_vulnerability/test.js, tests/java/lang/xml_external_entity_vulnerability/testdata/main.java
Add Java rule for XXE, for `DocumentBuilder.parse` and `JAXBContext` unmarshal method.
=> feat(java): add xxe rule

rules/java/lang/jwt_verification_bypass.yml, tests/java/lang/jwt_verification_bypass/test.js, tests/java/lang/jwt_verification_bypass/testdata/main.java
Add rule to catch use of `parse()` with JWT token as this does not perform signature verification
=> feat(java): add jwt missing signature verification

rules/go/lang/hardcoded_mysql_database_password.yml, rules/go/lang/hardcoded_pg_database_password.yml, rules/go/lang/observable_timing.yml, rules/go/lang/permissive_regex_validation.yml, rules/go/lang/ssl_verification.yml, rules/java/lang/ssl_hostname_verifier.yml, rules/java/third_parties/elasticsearch.yml, rules/javascript/lang/observable_timing.yml, scripts/rule_schema_v2.jsonc
Severity was not linted correctly, this means sometimes severity was missing. Replacements are based on similar rules for now we will review overall severity usage later.
=> fix: linting and missing rule severity

rules/go/lang/observable_timing.yml, rules/java/lang/observable_timing.yml, rules/javascript/lang/observable_timing.yml, tests/java/lang/observable_timing/test.js, tests/java/lang/observable_timing/testdata/main.java
Add Java rule for observable timing
Relates to [#197](https://github.com/Bearer/bearer-rules/issues/197)
=> feat(java): add observable timing rule

.github/workflows/lint.yml
Its possible for out of date branches to look ok on a PR and get merged only to be invalid. This makes sure we always lint main to find any issue that may have crept in.
=> ci: lint on main

.github/workflows/canary_integration_tests.yml, .github/workflows/integration_tests.yml
Enables tests for Go third party rules. Requires changes from https://github.com/Bearer/bearer/pull/1546
=> ci: enable go third party rule tests

rules/ruby/rails/render_using_user_input.yml, tests/ruby/rails/render_using_user_input/testdata/ok_not_unsafe.rb, tests/ruby/rails/render_using_user_input/testdata/unsafe.rb
Adds `send_data` to the Ruby on Rails XSS rule
=> fix(ruby): add missing rails XSS send_data case

rules/ruby/lang/http_url_using_user_input.yml, tests/ruby/lang/http_url_using_user_input/testdata/ok_not_unsafe.rb, tests/ruby/lang/http_url_using_user_input/testdata/unsafe_open.rb
Adds a pattern for `URI#read` to the Ruby SSRF rule
=> fix(ruby): add missing URI#read case

rules/ruby/rails/render_using_user_input.yml, tests/ruby/rails/render_using_user_input/testdata/ok_not_unsafe.rb, tests/ruby/rails/render_using_user_input/testdata/unsafe.rb
In the `ruby_rails_render_using_user_input` rule, only trigger for `send_data` when the disposition is `inline`, or when we are unsure of the disposition.
XSS is limited to the case when data is returned inline to a browser
- Close #357
=> fix(ruby): only consider inline disposition as xss for send_data

rules/go/lang/cookie_missing_http_only.yml, rules/go/lang/insecure_cookie.yml, tests/go/lang/cookie_missing_http_only/testdata/main.go, tests/go/lang/insecure_cookie/testdata/main.go
Fixes matching of the `true` case in the Go cookie rules. 
Previously these rules were matching secure cases as incorrect rule names were used in the `not` filter
- Close #351
=> fix(go): fix go cookie rules

rules/go/gosec/filesystem/poor_write_permissions.yml, tests/go/gosec/filesystem/poor_write_permissions/testdata/main.go
Extend current golang file permission rule so that it catches cases like `0o755`
=> fix(go): include 0oXXX for bad file permission

rules/go/gosec/injection/subproc_injection.yml, rules/go/shared/lang/dynamic_input.yml, rules/go/shared/lang/instance.yml, tests/go/gosec/filesystem/filereadtaint/testdata/main.go
* Add pattern to dynamic input rule to match on array (e.g. `insecure[0]`)
* Add scoping to subproc rule
* Fix missing var issue with lang instance rule
=> fix(golang): fixes following battletesting

rules/go/lang/missing_tls_minversion.yml, tests/go/lang/missing_tls_minversion/test.js, tests/go/lang/missing_tls_minversion/testdata/main.go
Add Golang rule to catch TLS configuration without MinVersion defined
=> feat(go): add TLS MinVersion rule

rules/go/gosec/sql/concat_sqli.yml, tests/go/gosec/sql/concat_sqli/test.js, tests/go/gosec/sql/concat_sqli/testdata/query_context.go
`QueryContext` and `ExecContext` can take three args, and our pattern was not accounting for this
Also add `client` as fallback for database instance
=> fix(go): QueryContext can take three args

rules/go/gosec/injection/subproc_injection.yml, tests/go/gosec/injection/subproc_injection/testdata/main.go
The scoping added here https://github.com/Bearer/bearer-rules/pull/365 causes a regression and we miss cases like `userName.Value` (see added test case)
=> fix: subproc injection rule

rules/go/gosec/filesystem/decompression_bomb.yml
Rule incorrectly labelled as CWE 327 when really it is [CWE 409 "Improper Handling of Highly Compressed Data (Data Amplification)"](https://cwe.mitre.org/data/definitions/409.html)
=> fix(golang): CWE for compression bomb rule

rules/go/lang/permissive_regex_validation.yml, rules/php/symfony/permissive_regex_validation.yml
Add clarification to the permissive regexp rules about why the boundary expressions `\A` and `\z`or `\Z` are recommended over `^` and `$`. 
Note, we do not add a clarification to the Rails permissive regexp rule, since for Ruby multiline mode is the default. 
Closes #366
=> fix: clarify permissive regexp rules

rules/php/lang/http_url_using_sensitive_data.yml
=> fix: typo in PHP rule description

rules/java/android/prevent_screenshot.yml, tests/java/android/prevent_screenshot/testdata/main.java
FLAG_SECURE should be set to ensure Android is not taking screenshots and to avoid tap-jacking attacks
Rule pattern was incorrect here. 
=> fix(java): incorrect android tapjacking rule

rules/javascript/lang/sql_injection.yml, rules/javascript/shared/common/external_input.yml, rules/php/lang/sql_injection.yml, rules/php/shared/lang/dynamic_input.yml, rules/php/shared/lang/external_input.yml, rules/php/symfony/sql_injection.yml, rules/ruby/rails/sql_injection.yml, rules/ruby/shared/common/dynamic_input.yml, rules/ruby/shared/common/external_input.yml, tests/javascript/lang/sql_injection/testdata/mysql2_sql_injection.js, tests/javascript/lang/sql_injection/testdata/ok_no_sql_injection.js, tests/javascript/lang/sql_injection/testdata/pg_sql_injection.js, tests/javascript/lang/sql_injection/testdata/sequelize_sql_injection.js, tests/php/lang/sql_injection/testdata/injection.php, tests/php/lang/sql_injection/testdata/safe.php, tests/php/symfony/sql_injection/testdata/injection.php, tests/ruby/rails/sql_injection/testdata/injected_params.rb, tests/ruby/rails/sql_injection/testdata/ok_sanitized.rb
Use external input (user and dynamic input) for all current SQLi rules. This may increase number of false positives for our SQLi rule, but we feel this is valid given the severity of the legitimate case of SQLi. That is, an FP is preferable to missing a valid injection vulnerability.
=> feat: expand SQLi rules for all GA languages

rules/javascript/lang/non_literal_fs_filename.yml, tests/javascript/lang/non_literal_fs_filename/testdata/app.js
Fix pattern for JS non-literal filename rule so that it does not catch on cases where e.g. filename is a string literal but subsequent args are not. 
Separate fs methods that take two filenames (e.g. `copyFile`)
Update test to reflect these cases
=> fix(js): non-literal filename rule

rules/java/shared/lang/dynamic_input.yml, rules/java/shared/lang/user_input.yml, rules/javascript/express/xml_external_entity_vulnerability.yml, rules/javascript/lang/sql_injection.yml, tests/java/lang/sqli/testdata/bad.java, tests/javascript/express/xml_external_entity_vulnerability/testdata/lib_xml_with_noent_true.js, tests/javascript/lang/sql_injection/test.js, tests/javascript/lang/sql_injection/testdata/sqlite3_sql_injection.js
* Fix Java dynamic and user input so that we still consider things like `external.toLowerCase()` as external input
* Add sqlite 3 case to JS SQLi rule
* Handle case with dynamic options for JS Express XXE LibXML case
=> fix: Java and JS SQLi rules and JS Express XXE rule

rules/python/lang/exception.yml, tests/python/lang/exception/test.js, tests/python/lang/exception/testdata/main.py
Add rule against sensitive data leaking in exception messages
=> feat(python): exception message rule (CWE-210)

rules/python/shared/lang/import1.yml, rules/python/shared/lang/import2.yml, rules/python/shared/lang/import3.yml, rules/python/shared/lang/import4.yml
Adds Python shared rules for handling imported names. These are specific to the number of nested levels of modules being imported.
=> feat(python): add shared rules for imports

rules/python/django/path_using_user_input.yml, rules/python/lang/path_using_user_input.yml, tests/python/django/path_using_user_input/test.js, tests/python/django/path_using_user_input/testdata/main.py, tests/python/lang/path_using_user_input/test.js, tests/python/lang/path_using_user_input/testdata/main.py
* Add shared user input rules for Python
* Add path using user input rules for Python lang and Django framework
=> feat(python): path traversal with user input (CWE 73)

rules/python/lang/code_injection.yml, tests/python/lang/code_injection/test.js, tests/python/lang/code_injection/testdata/main.py
Add Python rule for CWE-94 code injection
=> feat(python): code injection (CWE-94)

rules/python/lang/eval_using_user_input.yml
Fix new eval injection rule so that it uses the shared import rules
I leave the other existing Python rules as they are (hashing, etc), because they have yet to be updated in this GA phase. 
=> fix(python): use shared import for eval injection rule

rules/php/symfony/sql_injection.yml, tests/php/symfony/sql_injection/testdata/injection-query-builder.php
Extend PHP symfony SQLi sanitizer  to include `createNamedParameter()` and `setParameter()` methods
=> fix(php): symfony SQLi sanitizer

rules/python/django/path_traversal.yml, rules/python/lang/path_traversal.yml, tests/python/django/path_traversal/test.js, tests/python/django/path_traversal/testdata/main.py, tests/python/lang/path_traversal/test.js, tests/python/lang/path_traversal/testdata/main.py
Add Python rules for unsanitized input in path traversal (CWE-22)
=> feat(python): path traversal CWE-22

rules/python/lang/os_command_injection.yml, tests/python/lang/os_command_injection/test.js, tests/python/lang/os_command_injection/testdata/main.py
Add Python rule for CWE-78 OS command injection
=> feat(python): os command injection (CWE-78)

rules/python/shared/lang/instance.yml
Adds a shared rule for matching instances of a class. Matches the following examples:
```python
MatchedClass(a, b)
class Unimportant(MatchedClass):
def f(self, x): # self is matched as an instance
...
def m(x: MatchedClass): # x is matched as an instance
...
```
This can be composed with the import rules to match a specific type. eg:
```yaml
- pattern: $<INSTANCE>
filters:
- variable: INSTANCE
detection: python_shared_lang_instance
scope: cursor_strict
filters:
- variable: CLASS
detection: python_shared_lang_import2
scope: cursor
filters:
- variable: MODULE1
values: [http]
- variable: MODULE2
values: [server]
- variable: NAME
values: [BaseHTTPRequestHandler]
```
Needs: https://github.com/Bearer/bearer/pull/1597
If this is your first time contributing please [sign the …
=> feat(python): add shared instance rule

rules/python/django/cookies.yml, rules/python/lang/cookies.yml, rules/python/lang/logger.yml, rules/python/shared/django/http_response.yml, tests/python/django/cookies/test.js, tests/python/django/cookies/testdata/main.py, tests/python/lang/cookies/test.js, tests/python/lang/cookies/testdata/main.py
Add rule to catch sensitive data exposed in cookie value (CWE-315), for Python Django framework
=> feat(python): sensitive data in cookie rule (CWE-315)

rules/php/symfony/sql_injection.yml, tests/php/symfony/sql_injection/testdata/injection-query-builder.php
Both `createNamedParameter` and `setParameter` can take multiple arguments.
Update sanitizer method for SQLi rule to reflect this. 
=> fix(php)(symfony): multiple parameters for SQLi sanitization method

rules/python/lang/bind_to_all_interfaces.yml, tests/python/lang/bind_to_all_interfaces/test.js, tests/python/lang/bind_to_all_interfaces/testdata/main.py
Add Python rule to catch cases of binding to all interfaces, which can lead to unintentional information exposure over insecure network
=> feat(python): bind to all interfaces (CWE-200)

rules/python/django/debug_mode_enabled.yml, tests/python/django/debug_mode_enabled/test.js, tests/python/django/debug_mode_enabled/testdata/main.py
Add Django rule to catch `DEBUG = True` case which could lead to CWE-200
=> feat(python)(django): debug mode enabled (CWE-200)

rules/python/lang/code_injection.yml, rules/python/lang/reflection_using_user_input.yml, tests/python/lang/reflection_using_user_input/test.js, tests/python/lang/reflection_using_user_input/testdata/main.py
Add Python rule for reflection with user input (CWE-470)
This takes `getattr` from code injection rule because it is closer to CWE-470 than CWE-94
=> feat(python): add unsafe reflection rule (CWE-470)

.github/workflows/canary_integration_tests.yml, .github/workflows/integration_tests.yml, rules/python/django/response_using_user_input.yml, rules/python/django/template_injection.yml, rules/python/lang/http_response_splitting.yml, rules/python/lang/manual_html_sanitization.yml, rules/python/lang/raw_html_using_user_input.yml, rules/python/shared/common/html_user_input.yaml, rules/python/shared/django/html_sanitizer.yml, rules/python/shared/django/user_input.yml, rules/python/shared/lang/user_input.yml, tests/python/django/response_using_user_input/test.js, tests/python/django/response_using_user_input/testdata/main.py, tests/python/django/template_injection/test.js, tests/python/django/template_injection/testdata/main.py, tests/python/lang/http_response_splitting/test.js, tests/python/lang/http_response_splitting/testdata/main.py, tests/python/lang/manual_html_sanitization/test.js, tests/python/lang/manual_html_sanitization/testdata/main.py, tests/python/lang/raw_html_using_user_input/test.js, tests/python/lang/raw_html_using_user_input/testdata/main.py
Needs https://github.com/Bearer/bearer/pull/1607
=> feat(python): add cwe-79 xss rules

rules/php/lang/weak_hash_adler32.yml, rules/python/lang/weak_hash_adler32.yml, rules/python/lang/weak_hash_crc32.yml, rules/python/lang/weak_hash_dss.yml, rules/python/lang/weak_hash_md5.yml, rules/python/lang/weak_hash_sha1.yml, tests/python/lang/weak_hash_adler32/test.js, tests/python/lang/weak_hash_adler32/testdata/main.py, tests/python/lang/weak_hash_crc32/test.js, tests/python/lang/weak_hash_crc32/testdata/main.py, tests/python/lang/weak_hash_dss/test.js, tests/python/lang/weak_hash_dss/testdata/main.py, tests/python/lang/weak_hash_md5/testdata/bad.py, tests/python/lang/weak_hash_sha1/testdata/bad.py
Adds Python CWE-328 rules for weak hash algorithms
=> feat(python): add cwe-328 weak hash rules

rules/python/django/open_redirect.yml, tests/python/django/open_redirect/test.js, tests/python/django/open_redirect/testdata/main.py
Adds a Python Django rule for CWE-601 open redirects
=> feat(python): add cwe-601 open redirect rule

.github/workflows/canary_integration_tests.yml, .github/workflows/integration_tests.yml, rules/python/shared/aws_lambda/user_input.yml, rules/python/shared/common/user_input.yml, rules/python/third_parties/aws_query_injection.yml, tests/python/third_parties/aws_query_injection/test.js, tests/python/third_parties/aws_query_injection/testdata/main.py
Add Python AWS DynamoDB / SimpleDB rule to catch NoSQLi 
Add Python AWS Lambda user input (to support new rule)
Add Python third parties folder to CI
=> feat(python): AWS DynamoDB / SimpleDB NoSQLi (CWE 943)

rules/python/django/path_using_user_input.yml, tests/python/django/path_using_user_input/testdata/main.py
Fix FileSystemStorage call pattern and testdata
=> fix(python/django): FileSystemStorage call

rules/python/lang/ssl_verification.yml, tests/python/lang/ssl_verification/test.js, tests/python/lang/ssl_verification/testdata/main.py
Add rule against disabling or making optional the verification of SSL certificates
Looking at urllib3, ssl, and requests libraries
=> feat(python): add lang rule for ssl certificate verification (CWE-295)

rules/python/django/permissive_allow_origin.yml, rules/python/lang/permissive_allow_origin.yml, tests/python/django/permissive_allow_origin/test.js, tests/python/django/permissive_allow_origin/testdata/main.py, tests/python/lang/permissive_allow_origin/test.js, tests/python/lang/permissive_allow_origin/testdata/main.py
Add Python lang and Django rules for allow origin set to anything (`"*"`)
=> feat(python): add permissive cross domain policy rule (CWE-942)

rules/python/django/insecure_allow_origin.yml, rules/python/lang/insecure_allow_origin.yml, tests/python/django/insecure_allow_origin/test.js, tests/python/django/insecure_allow_origin/testdata/main.py, tests/python/lang/insecure_allow_origin/test.js, tests/python/lang/insecure_allow_origin/testdata/main.py
Add Python lang and Django rules to catch allow origin headers set to user input
=> feat(python): insecure allow origin (CWE-346)

rules/python/django/insecure_cookie_settings.yml, tests/python/django/insecure_cookie_settings/test.js, tests/python/django/insecure_cookie_settings/testdata/main.py
Add rule for insecure configuration of Django cookie settings - CWE-693
=> feat(python/django): secure configuration failure (CWE-693)

rules/python/third_parties/datadog.yml, tests/python/third_parties/datadog/test.js, tests/python/third_parties/datadog/testdata/main.py
Add Python third parties rule for Datadog
=> feat(python): add datadog third parties rule (CWE-201)

rules/python/third_parties/airbrake.yml, tests/python/third_parties/airbrake/test.js, tests/python/third_parties/airbrake/testdata/main.py
Add Python Airbrake rule (Pybrake)
=> feat(python): add airbrake third parties rule (CWE-201)

rules/python/lang/deserialization_of_user_input.yml, rules/python/third_parties/airbrake.yml
* Fix pattern issue in Airbrake rule
* Fix typo in pattern variable for deserialization rule
It seems these kinds of issues are not picked up by our schema validator or by the bearer-rules unit tests, but rather cause null pointer issues in the engine when run on real-world repositories (which is done manually as part of the release process). We need to investigate why the unit tests for these two rules were able to pass -- seems strange that they were working 🤔 
=> fix: python rules

rules/python/third_parties/elasticsearch.yml, tests/python/third_parties/elasticsearch/test.js, tests/python/third_parties/elasticsearch/testdata/main.py
Add Python third party rule for Elasticsearch
=> feat(python): add elasticsearch third party rule (CWE-201)

rules/python/third_parties/open_telemetry.yml, tests/python/third_parties/open_telemetry/test.js, tests/python/third_parties/open_telemetry/testdata/main.py
Add Python third party rule for OpenTelemetry
=> feat(python): add OpenTelemetry third party rule (CWE-201)

rules/python/third_parties/rollbar.yml, tests/python/third_parties/rollbar/test.js, tests/python/third_parties/rollbar/testdata/main.py
Add Python third party Rollbar rule
=> feat(python): add rollbar third party rule (CWE-201)

rules/go/third_parties/open_telemetry.yml, rules/java/third_parties/open_telemetry.yml, rules/javascript/third_parties/open_telemetry.yml, rules/php/third_parties/open_telemetry.yml, rules/ruby/third_parties/open_telemetry.yml
=> fix: opentelemetry typo

rules/python/django/sql_injection.yml, rules/python/lang/sql_injection.yml, tests/python/django/sql_injection/testdata/main.py, tests/python/lang/sql_injection/testdata/main.py
Add patterns for more libraries:
* pg8000
* asyncpg
and Django's `expression.RawSQL`
=> feat(python): extend SQLi rules

rules/python/django/cookie_missing_http_only.yml, rules/python/django/cookie_missing_secure.yml, rules/python/django/crlf_injection.yml, rules/python/django/csrf_protection_disabled.yml, rules/python/lang/deserialization_of_user_input.yml, rules/python/lang/weak_password_encryption_md5.yml, rules/python/lang/weak_password_encryption_sha1.yml, rules/python/lang/xml_external_entity_vulnerability.yml, rules/python/shared/django/http_response.yml, rules/python/shared/lang/dynamic_input.yml, tests/python/django/cookie_missing_http_only/test.js, tests/python/django/cookie_missing_http_only/testdata/main.py, tests/python/django/cookie_missing_secure/test.js, tests/python/django/cookie_missing_secure/testdata/main.py, tests/python/django/crlf_injection/test.js, tests/python/django/crlf_injection/testdata/main.py, tests/python/django/csrf_protection_disabled/test.js, tests/python/django/csrf_protection_disabled/testdata/main.py, tests/python/lang/weak_password_encryption_md5/testdata/bad.py, tests/python/lang/xml_external_entity_vulnerability/test.js, tests/python/lang/xml_external_entity_vulnerability/testdata/main.py
Add missing rules
* Django cookies missing secure settings
* Django CSRF exempt usage
* Django CRLF sanitization
* Python XXE 
Extend existing rules
* Django HTTP response object
* Dynamic input to include vars passed to functions
* Add missing pickle methods to eserialization rule
* Fix password hashing rules so that they use correct import helpers
=> feat(python): add missing rules from goat project review

rules/python/third_parties/clickhouse.yml
Update Python 3rd Party Clickhouse pattern to use instance as well as import
=> fix(python): import for clickhouse rule

rules/python/lang/xml_external_entity_vulnerability.yml
To be consistent with the XXE rules in other languages, CWE-611 should be critical severity 
=> fix(python): incorrect severity for XXE rule

rules/java/third_parties/clickhouse.yml, rules/php/third_parties/clickhouse.yml
Java and PHP have the same copy-pasta typo that Ruby had 🙈 
=> fix: typos in ClickHouse rules

rules/go/lang/permissive_regex_validation.yml, tests/go/lang/permissive_regex_validation/testdata/main.go
Ideally the `go_lang_permissive_regex_validation` rule would only trigger when the permissive regular expression is being used for validation-specific purposes. Unlike some frameworks (Ruby-on-Rails, PHP Symfony), with golang, we cannot determine how a particular regular expression is being used. For this reason, the rule was triggering on the compilation of permissive regex, rather than its use. However, this meant that we were seeing some confusing false positives with this rule -- for example, with `Replace` (where there is no real security issue).
To address this, we modify the rule so that it triggers only when a permissive regular expression is used with `Match` methods, as this is more likely to be a validation case. We hope that this will reduce the rate of false positives while …
=> fix(golang): permissive regex rule for validation purposes

rules/go/gosec/file_permissions/file_perm.yml, rules/go/gosec/file_permissions/mkdir.yml, rules/go/gosec/filesystem/poor_write_permissions.yml, rules/java/android/world_readable_writable_mode.yml, rules/javascript/lang/file_permissions.yml, rules/python/django/file_permissions.yml, rules/python/lang/file_permissions.yml
Replace CWE-276: Incorrect Default Permissions:
> During installation, installed file permissions are set to allow anyone to modify those files. 
with CWE-732: Incorrect Permission Assignment for Critical Resource:
> The product specifies permissions for a security-critical resource in a way that allows that resource to be read or modified by unintended actors. 
=> fix: use more appropriate cwe for file permission rules

rules/java/spring/model_reflected_xss.yml, tests/java/spring/model_reflected_xss/test.js, tests/java/spring/model_reflected_xss/testdata/main.java
Add rule for reflected XSS in spring UI model.
=> feat(java): add rule for spring ui model

rules/go/lang/deserialization_of_user_input.yml
Encoding user input isn't itself unsafe until this input is decoded. We therefore remove the serialization case to keep consistent with our other CWE-502 rules which are directly concerned with the deserialization of user input. 
=> fix(golang): remove encoder pattern from deserialization rule (CWE-502)

rules/ruby/rails/sql_injection.yml, tests/ruby/rails/sql_injection/test.js, tests/ruby/rails/sql_injection/testdata/injected_params.rb, tests/ruby/rails/sql_injection/testdata/shared_methods.rb
Some Active Record methods that are vulnerable to SQL injection are also methods used by e.g. the Enumerable class (such as `count`, `sum`). This can result in a lot of false positives from Ruby's SQLi rule. 
In this PR, we tighten the SQLi patterns for these shared methods. Namely, 
* Limit caller to a suspected Active Record model (starts with a capital, but is not all caps) or associations (ends with an `s`)
* Remove naked pattern (no caller)
Alternate solutions considered: 
1. Remove these shared methods entirely, given their propensity for false positives. Rejected because there is no sanitization on Active Record's end, making these methods (`count` especially) quite dangerous if exposed to SQL injection
2. Restrict to user input instead of dynamic input. Rejected because a decision …
=> fix(ruby): tighten sql injection patterns

rules/python/shared/common/sql_user_input.yml, tests/python/lang/sql_injection/testdata/main.py
Extend sanitizer pattern to include `MySQLConverter.escape()`
=> fix(python): update sql sanitizer

rules/javascript/lang/sql_injection.yml, tests/javascript/lang/sql_injection/testdata/mysql2_sql_injection.js
If we make a promise from a MySQL pool instance, the SQL injection rule loses track of any injection cases happening with this now-async pool instance. 
An alternative would be to consider the `promise()` method a "reflexive" method in the engine, but I didn't go this route for two reasons: (a.) it's not a true reflexive method (`x.promise()` is strictly not the same as `x`) and (b.) this would require an additional scope change to the SQL injection rule (from cursor to result) which again suggests to me that it's not the way to go.
=> fix(javascript): handle mysql pool as a promise

rules/go/lang/cross_site_scripting.yml, rules/java/lang/xml_external_entity_vulnerability.yml, rules/javascript/express/xml_external_entity_vulnerability.yml, rules/javascript/lang/sql_injection.yml, rules/php/lang/sql_injection.yml, rules/php/lang/xml_external_entity_vulnerability.yml, rules/ruby/lang/sql_injection.yml, rules/ruby/lang/xml_external_entity_vulnerability.yml, tests/go/lang/cross_site_scripting/test.js, tests/go/lang/cross_site_scripting/testdata/main.go, tests/java/lang/xml_external_entity_vulnerability/testdata/main.java, tests/javascript/express/xml_external_entity_vulnerability/testdata/ok_no_xxe_vuln_present.js, tests/javascript/express/xml_external_entity_vulnerability/testdata/xxe_vuln_with_xml2js.js, tests/javascript/lang/sql_injection/testdata/ok_no_sql_injection.js, tests/php/lang/sql_injection/testdata/injection.php, tests/php/lang/sql_injection/testdata/safe.php, tests/php/lang/xml_external_entity_vulnerability/testdata/bad.php, tests/php/lang/xml_external_entity_vulnerability/testdata/ok.php, tests/ruby/lang/sql_injection/test.js, tests/ruby/lang/sql_injection/testdata/main.rb, tests/ruby/lang/xml_external_entity_vulnerability/test.js, tests/ruby/lang/xml_external_entity_vulnerability/testdata/main.rb, tests/ruby/lang/xml_external_entity_vulnerability/testdata/ok.rb
Update and fix some existing rules
Add support for XXE and non-active record SQLi in Ruby as well as XSS in Golang
=> feat: rule improvements

.github/workflows/lint.yml, CONTRIBUTING.md, README.md
Remove links to discord in docs as its mostly inactive.
=> docs: remove discord links
