- .github/workflows/release.yml
This action will tag and create release archives for rules by language
> feat: add release action

- .github/workflows/lint_pr.yml
copy over some PR linting from bearer/bearer
> ci: lint pr titles

- .gitignore
> chore: add gitignore file

- test.sh
> chore: remove test file

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
- .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
- .github/PULL_REQUEST_TEMPLATE.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- SECURITY.md
Add various docs to the project around contributing
> docs: add info about project issues etc

- .github/workflows/integration_tests.yml
Split integration tests to hopefully increase overall speed!
> ci: split test runners

- javascript/aws_lambda/sql_injection.yml
- javascript/aws_lambda/sql_injection/.snapshots/knex_sql_injection.yml
- javascript/aws_lambda/sql_injection/.snapshots/mysql2_sql_injection.yml
- javascript/aws_lambda/sql_injection/.snapshots/pg_sql_injection.yml
- javascript/aws_lambda/sql_injection/.snapshots/sequelize_sql_injection.yml
- reindent code in markdown ([javascript/aws_lambda/sql_injection.yml](https://github.com/Bearer/bearer-rules/pull/31#diff-a3bdabf70331dc9ddbb52ecadec6208959ef9d3f7674aba95bffb86a6126cc5b))
> docs: update description in javascript/aws_lambda/sql_injection.yml

- javascript/lang/logger/.snapshots/console.yml
- javascript/third_parties/algolia/.snapshots/datatype_in_save_object.yml
- javascript/third_parties/bugsnag/.snapshots/datatype_in_start.yml
- javascript/third_parties/new_relic/.snapshots/datatype_in_interaction_set_attribute.yml
- javascript/third_parties/segment/.snapshots/datatype_in_identify.yml
- javascript/third_parties/segment/.snapshots/datatype_in_track.yml
- ruby/lang/http_get_params/.snapshots/datatype_in_params.yml
- ruby/lang/weak_encryption/.snapshots/blowfish_data.yml
- ruby/lang/weak_encryption/.snapshots/openssl_rsa_data.yml
- ruby/rails/sql_injection/.snapshots/injected_params.yml
- ruby/third_parties/airbrake/.snapshots/datatype_in_extended_notify_methods.yml
- ruby/third_parties/airbrake/.snapshots/datatype_in_notify.yml
- ruby/third_parties/honeybadger/.snapshots/honeybadger_context.yml
- ruby/third_parties/honeybadger/.snapshots/honeybadger_notify.yml
- ruby/third_parties/new_relic/.snapshots/datatype_in_add_custom_parameters.yml
- ruby/third_parties/open_telemetry/.snapshots/datatype_in_span_attributes.yml
- ruby/third_parties/rollbar/.snapshots/datatype_in_log_helper.yml
Latest release fixed some issues with finding fingerprinting so snapshots need updating
> fix: snapshot fingerprints from 1.4

- java/lang/logger.yml
- java/lang/logger/.snapshots/simple.yml
- java/lang/path_traversal.yml
- java/lang/path_traversal/.snapshots/cookie_file_traversal.yml
- java/lang/path_traversal/.snapshots/request_file_traversal.yml
- java/lang/sqli.yml
- java/lang/sqli/.snapshots/string_concatenation.yml
- java/lang/weak_encryption.yml
- java/lang/weak_encryption/.snapshots/md5_encryption.yml
This pr adds remediation messages and cwe ids for java rules
> feat: java rules docs

- .github/workflows/canary.yml
- .github/workflows/release.yml
Ensure shared rules are added to the tarballs for each language during release.
> ci: package shared rules

- .gitignore
- java/lang/desede_usage.yml
- java/lang/desede_usage/.snapshots/deprecated.yml
- java/lang/desede_usage/testdata/deprecated.java
- java/lang/ldap_injection.yml
- java/lang/ldap_injection/.snapshots/ldap_injection.yml
- java/lang/ldap_injection/testdata/ldap_injection.java
- java/lang/xpath_injection.yml
- java/lang/xpath_injection/.snapshots/xpath_injection.yml
- java/lang/xpath_injection/testdata/xpath_injection.java
- java/lang/xss_response_writer.yml
- java/lang/xss_response_writer/.snapshots/vulnerable.yml
- java/lang/xss_response_writer/testdata/vulnerable.java
Add desde and response writer rules
> feat(java): add desde and xss response writer

- java/lang/path_traversal.yml
Add more methods to path traversal rule
Relates to #44
> feat(java): extend path traversal rule

- java/lang/weak_hash_md5/.snapshots/md5_hash.yml
- javascript/lang/file_generation/.snapshots/file_generation.yml
- javascript/lang/weak_hash_md5/.snapshots/md5.yml
- javascript/third_parties/algolia/.snapshots/datatype_in_save_object.yml
- javascript/third_parties/bugsnag/.snapshots/datatype_in_start.yml
- javascript/third_parties/new_relic/.snapshots/datatype_in_interaction_set_attribute.yml
- javascript/third_parties/segment/.snapshots/datatype_in_identify.yml
- javascript/third_parties/segment/.snapshots/datatype_in_track.yml
- ruby/lang/cookies/.snapshots/datatype_in_signed_cookies.yml
- ruby/lang/file_generation/.snapshots/datatype_in_csv_generate.yml
- ruby/lang/file_generation/.snapshots/datatype_in_csv_open.yml
- ruby/lang/file_generation/.snapshots/datatype_in_file_open.yml
- ruby/lang/http_get_params/.snapshots/datatype_in_params.yml
- ruby/lang/jwt/.snapshots/datatypes_with_encrypted_jwt.yml
- ruby/lang/weak_encryption_dsa/.snapshots/openssl_dsa_data.yml
- ruby/lang/weak_encryption_rc4/.snapshots/rc4_data.yml
- ruby/lang/weak_encryption_rsa/.snapshots/openssl_rsa_data.yml
- ruby/third_parties/airbrake/.snapshots/datatype_in_extended_notify_methods.yml
- ruby/third_parties/honeybadger/.snapshots/honeybadger_notify.yml
- ruby/third_parties/new_relic/.snapshots/datatype_in_add_custom_parameters.yml
- ruby/third_parties/rollbar/.snapshots/datatype_in_log.yml
- ruby/third_parties/rollbar/.snapshots/datatype_in_log_helper.yml
- ruby/third_parties/rollbar/.snapshots/datatype_in_scope.yml
Fix fingerprints for https://github.com/Bearer/bearer/pull/1102
> fix: fingerprints

- javascript/express/hardcoded_secret.yml
- javascript/express/hardcoded_secret/.snapshots/hardcoded_secret_in_jwt.yml
- javascript/express/hardcoded_secret/.snapshots/hardcoded_secret_in_session.yml
- javascript/lang/hardcoded_secret.yml
- javascript/lang/hardcoded_secret/.snapshots/insecure_assigment.yml
- javascript/lang/hardcoded_secret/.snapshots/insecure_crypto.yml
- javascript/lang/hardcoded_secret/.snapshots/insecure_object.yml
Extend remediation copy for JS hardcoded secret rules
Fixes #140
> docs(js): extend remediation copy for hardcoded secret rules

- scripts/invoke.sh
When we fixed exit code bug in the main repo we changed the exit code on the tests
> ci: bug with exit code in test invoker

- rules/java/lang/ldap_injection.yml
- rules/java/lang/xss_response_writer.yml
- rules/java/shared/lang/user_input.yml
- rules/javascript/lang/manual_html_sanitization.yml
- rules/javascript/shared/lang/import_member.yml
- rules/ruby/lang/path_using_user_input.yml
- rules/ruby/lang/regex_using_user_input.yml
- rules/ruby/rails/sql_injection.yml
- rules/ruby/shared/rails/user_input.yml
- scripts/rule_schema.json
Makes some additional changes to improve compatibility with the coming CLI changes in https://github.com/Bearer/bearer/pull/1206.
Also fixes some issues introduced in https://github.com/Bearer/bearer-rules/pull/151
> fix: fixes for compatibility with latest cli

- tests/java/lang/os_command_injection/__snapshots__/test.js.snap
- tests/java/lang/sqli/__snapshots__/test.js.snap
- tests/java/lang/xpath_injection/__snapshots__/test.js.snap
- tests/javascript/lang/file_generation/__snapshots__/test.js.snap
- tests/javascript/lang/logger/__snapshots__/test.js.snap
- tests/javascript/lang/manual_html_sanitization/__snapshots__/test.js.snap
- tests/javascript/third_parties/new_relic/__snapshots__/test.js.snap
- tests/ruby/lang/http_url_using_user_input/__snapshots__/test.js.snap
- tests/ruby/lang/manual_html_sanitization/__snapshots__/test.js.snap
- tests/ruby/lang/raw_html_using_user_input/__snapshots__/test.js.snap
- tests/ruby/rails/sql_injection/__snapshots__/test.js.snap
- tests/ruby/third_parties/open_telemetry/__snapshots__/test.js.snap
Update snapshots following last release
> chore: update snapshots

- rules/javascript/express/jwt_not_revoked.yml
Wait for https://github.com/Bearer/bearer/pull/1287 to be deployed (and maybe 1 week to release to give time to people to update?)
> feat(javascript): revert result scope in jwt_not_revoked rule

- scripts/rule_schema.jsonc
- scripts/validate.sh
Be more restrictive when checking the languages
Also replaces `json` by `jsonc` so that we can add comments to it :D
> ci: improve schema

- rules/ruby/rails/insecure_http_password.yml
- rules/ruby/rails/open_redirect.yml
- tests/ruby/rails/insecure_http_password/__snapshots__/test.js.snap
- tests/ruby/rails/open_redirect/__snapshots__/test.js.snap
Expand some missing or overly succinct remediation messages
> fix: add missing remediation

- rules/go/gosec/http/http_slowloris.yml
- tests/go/gosec/http/http_slowloris/__snapshots__/test.js.snap
- tests/go/gosec/http/http_slowloris/testdata/main.go
> fix: improve slowloris rule

- tests/helper.js
Show console message for debug purposes for new invoker
> test: improve helper.js for new invoker

- tests/php/lang/http_insecure/__snapshots__/test.js.snap
- tests/php/lang/ssl_verification/__snapshots__/test.js.snap
- tests/php/lang/weak_hash_md/__snapshots__/test.js.snap
- tests/php/lang/weak_hash_sha1/__snapshots__/test.js.snap
- tests/python/lang/weak_hash_md5/__snapshots__/test.js.snap
- tests/python/lang/weak_hash_sha1/__snapshots__/test.js.snap
- tests/ruby/lang/insecure_ftp/__snapshots__/test.js.snap
- tests/ruby/rails/insecure_smtp/__snapshots__/test.js.snap
- tests/ruby/rails/weak_custom_key/__snapshots__/test.js.snap
> test: update snapshots for canary

- scripts/write_v2_testfile.js
We can add the rule name to the helper comment because it is also helpful
> fix: improve test helper script

- package.json
- scripts/bulk_update.js
- yarn.lock
Bulk updater closes #218
run example:
```
yarn bulk-update ~/my-updates.csv
```
> feat: bulk update script

- rules/java/lang/open_redirect.yml
- tests/java/lang/open_redirect/test.js
- tests/java/lang/open_redirect/testdata/main.java
Add open redirect rule for Java
> feat(java): open redirect rule (CWE-601)

- rules/java/lang/http_url_using_user_input.yml
- tests/java/lang/http_url_using_user_input/test.js
- tests/java/lang/http_url_using_user_input/testdata/main.java
> feat(java): add SSRF rule (CWE-918)

- rules/java/third_parties/aws_query_injection.yml
- tests/java/third_parties/aws_query_injection/test.js
- tests/java/third_parties/aws_query_injection/testdata/main.java
Add AWS query injection rule for Java / AWSSimpleDB
> feat(java): add AWS query injection rule (CWE-943)

- tests/java/lang/code_injection/testdata/main.java
Update the testdata so that it is valid code. Before, we were referencing a variable that had not been not set.
> fix: java testdata for code injection rule

- rules/java/lang/exception.yml
- tests/java/lang/exception/test.js
- tests/java/lang/exception/testdata/main.java
Add Java rule to exception that leaks sensitive data
> feat(java): exception rule (CWE-210)

- rules/java/lang/cookie_leak.yml
- tests/java/lang/cookie_leak/test.js
- tests/java/lang/cookie_leak/testdata/main.java
Add rule to catch cookies that are leaking sensitive data
> feat(java): add cookie leaks rule (CWE-315)

- rules/java/lang/reflection_using_user_input.yml
- tests/java/lang/reflection_using_user_input/test.js
- tests/java/lang/reflection_using_user_input/testdata/main.java
Add Java rule for unsafe reflection
> feat(java): unsafe reflection (CWE-470)

- rules/java/third_parties/airbrake_javabrake.yml
- tests/java/third_parties/airbrake_javabrake/test.js
- tests/java/third_parties/airbrake_javabrake/testdata/main.java
Add rule for sensitive data leakage with Java Airbrake
> feat(java): airbrake library (CWE-201)

- rules/java/third_parties/clickhouse.yml
- tests/java/third_parties/clickhouse/test.js
- tests/java/third_parties/clickhouse/testdata/main.java
Add Java third party rule for ClickHouse API
> feat(java): third parties clickhouse rule

- rules/java/third_parties/bugsnag.yml
- tests/java/third_parties/bugsnag/test.js
- tests/java/third_parties/bugsnag/testdata/main.java
Add Java rule for Bugsnag leakage
> feat(java): add third parties bugsnag rule (CWE-201)

- rules/java/third_parties/datadog.yml
- rules/php/third_parties/datadog.yml
- tests/java/third_parties/datadog/test.js
- tests/java/third_parties/datadog/testdata/main.java
Add third party Java rule for Datadog
> feat(java): add third parties Datadog (CWE-201)

- tests/helper.js
> chore: use sink instead of source

- rules/java/third_parties/algolia.yml
- rules/java/third_parties/sentry.yml
- tests/java/third_parties/sentry/test.js
- tests/java/third_parties/sentry/testdata/main.java
Add third party Java rule for Sentry
> feat(java): third parties sentry

- rules/go/lang/open_redirect.yml
- tests/go/lang/open_redirect/test.js
- tests/go/lang/open_redirect/testdata/main.go
> feat(golang): add open redirect rule

- rules/go/lang/ssl_verification.yml
- scripts/invoke.sh
- tests/go/lang/ssl_verification/test.js
- tests/go/lang/ssl_verification/testdata/main.go
- tests/helper.js
Add CWE 295 ssl verification
Related https://github.com/Bearer/bearer-rules/issues/271
> feat(golang): add CWE 295 ssl verification

- rules/javascript/lang/insufficiently_random_values.yml
- tests/javascript/lang/insufficiently_random_values/test.js
- tests/javascript/lang/insufficiently_random_values/testdata/app.js
Add CWE 330
Related https://github.com/Bearer/bearer-rules/issues/278
> feat(js): add insuffiently random values

- rules/javascript/lang/file_permissions.yml
- tests/javascript/lang/file_permissions/test.js
- tests/javascript/lang/file_permissions/testdata/app.js
Add CWE 276
Related https://github.com/Bearer/bearer-rules/issues/278
> feat(js): add file permissions CWE 276

- rules/javascript/lang/logger_leak.yml
- tests/javascript/lang/logger_leak/test.js
- tests/javascript/lang/logger_leak/testdata/app.js
Related to https://github.com/Bearer/bearer-rules/issues/278
> chore: add log leakage generic

- tests/java/lang/weak_encryption_des/__snapshots__/test.js.snap
- tests/java/lang/weak_password_encryption_des/__snapshots__/test.js.snap
> ci(java): update some snapshots

- rules/go/gosec/file_permissions/file_perm.yml
- rules/go/gosec/file_permissions/mkdir.yml
- rules/go/lang/observable_timing.yml
- rules/javascript/lang/file_permissions.yml
- rules/javascript/lang/observable_timing.yml
- tests/javascript/lang/observable_timing/test.js
- tests/javascript/lang/observable_timing/testdata/app.js
Also improves file perm regex for MASK
> feat: add timing attack js

- scripts/generate/testJSContent.js
> chore: update testJSContent.js

- rules/javascript/lang/unsafe_deserialization.yml
> fix: add missing severity

- rules/go/gosec/http/http_slowloris.yml
- tests/go/gosec/http/http_slowloris/test.js
- tests/go/gosec/http/http_slowloris/testdata/main.go
The tests were not correct when we generated the snapshots.
> fix: update slowloris gosec

- rules/go/lang/observable_timing.yml
- rules/go/lang/permissive_regex_validation.yml
> fix: missing description and message

- rules/go/shared/lang/dynamic_request_input.yml
- tests/go/lang/html_tag_injection/test.js
- tests/go/lang/html_tag_injection/testdata/app.go
Improve dynamic request input shared rule which was the source of the tests failing.
- Close #286
> feat(go): fix missing input type

- rules/javascript/lang/path_traversal.yml
- rules/javascript/shared/common/dynamic_input.yml
- scripts/invoke.sh
- tests/javascript/express/path_traversal/test.js
- tests/javascript/express/path_traversal/testdata/path_traversal.ts
- tests/javascript/lang/path_traversal/test.js
- tests/javascript/lang/path_traversal/testdata/path_traversal.ts
> feat(js): add path traversal from dynamic input

- rules/javascript/express/path_traversal.yml
- rules/javascript/lang/observable_timing.yml
- rules/javascript/lang/path_traversal.yml
Fix scope for path
Also be more specific on observable timing considering https://github.com/Bearer/bearer/pull/1522
> fix: improve path traversal

- .github/workflows/canary.yml
- .github/workflows/canary_integration_tests.yml
- .github/workflows/integration_tests.yml
- .github/workflows/release.yml
> chore: update checkout to use node20

- CONTRIBUTING.md
- scripts/generate/ruleYAMLContent.js
- scripts/generate/testJSContent.js
- scripts/generate_rule.js
- Improve rule gen tooling based on recent feedback around usage.
- fix issues with namespaces that where more than one word
- auto create new namespaces
- fix pathing for tests
- #328
- closes #326
> feat(tools): improve rule gen

- rules/javascript/lang/dynamic_os_command.yml
> fix: fix typo in dynamic os command

- rules/ruby/third_parties/appsignal.yml
- tests/ruby/third_parties/appsignal/test.js
- tests/ruby/third_parties/appsignal/testdata/directly_appsignal.rb
- tests/ruby/third_parties/appsignal/testdata/set_sample_data.rb
- tests/ruby/third_parties/appsignal/testdata/with_block.rb
Add third party Ruby rule for AppSignal
> feat(ruby): add third parties AppSignal (CWE-201)

- scripts/invoke.sh
- tests/helper.js
related to https://github.com/Bearer/bearer/pull/1539
> chore: update path to main

- rules/go/lang/observable_timing.yml
- rules/javascript/lang/observable_timing.yml
> fix: duplicate severity

- rules/go/third_parties/elasticsearch.yml
- tests/go/third_parties/elasticsearch/test.js
- tests/go/third_parties/elasticsearch/testdata/main.go
Adds an ElasticSearch rule for Go.
> feat(go): add elasticsearch rule

- rules/go/third_parties/new_relic.yml
- tests/go/third_parties/new_relic/test.js
- tests/go/third_parties/new_relic/testdata/main.go
> feat(go): add new relic rule

- rules/go/shared/lang/instance.yml
- rules/go/third_parties/honeybadger.yml
- tests/go/third_parties/honeybadger/test.js
- tests/go/third_parties/honeybadger/testdata/main.go
Adds a Go rule for Honeybadger
> feat(go): add honeybadger rule

- rules/go/third_parties/open_telemetry.yml
- tests/go/third_parties/open_telemetry/test.js
- tests/go/third_parties/open_telemetry/testdata/main.go
Adds a Go rule for Open Telemetry.
> feat(go): add open telemetry rule

- rules/go/third_parties/segment.yml
- tests/go/third_parties/segment/test.js
- tests/go/third_parties/segment/testdata/main.go
Adds a Go privacy rule for Segment
> feat(go): add segment rule

- rules/go/third_parties/rollbar.yml
- tests/go/third_parties/rollbar/test.js
- tests/go/third_parties/rollbar/testdata/main.go
> feat(go): add rollbar rule

- rules/go/third_parties/sentry.yml
- tests/go/third_parties/sentry/test.js
- tests/go/third_parties/sentry/testdata/main.go
Adds a Go privacy rule for Sentry
> feat(go): add sentry rule

- rules/go/third_parties/google_dataflow.yml
- tests/go/third_parties/google_dataflow/test.js
- tests/go/third_parties/google_dataflow/testdata/main.go
Adds a Go privacy rule for Google Dataflow
> feat(go): add google dataflow rule

- scripts/generate/ruleYAMLContent.js
Add severity key to rule YAML template
> fix: add severity to rule template

- package.json
- rules/go/gosec/crypto/weak_tls_version.yml
- rules/go/gosec/filesystem/tempfile.yml
- rules/go/gosec/filesystem/ziparchive.yml
- rules/go/gosec/leak/pprof_endpoint.yml
- rules/go/lang/observable_timing.yml
- rules/java/lang/observable_timing.yml
- rules/javascript/lang/observable_timing.yml
- scripts/validate_rule_urls.js
Add a helper script to find invalid or broken URLs
Update or remove invalid URLs
> fix: normalize rule links

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
Added CLA see https://github.com/Bearer/bearer/pull/1563 for more details
> docs: add contributor license agreement

- rules/javascript/express/nosql_injection.yml
- tests/javascript/express/nosql_injection/test.js
- tests/javascript/express/nosql_injection/testdata/app.js
Add JS Express rule for MongoDB NoSQL injection
> feat(js): add mongoDB NoSQLi rule

- .github/workflows/integration_tests.yml
Typo introduced from local debugging of https://github.com/Bearer/bearer-rules/pull/384
> fix: typo in integration_tests.yml

- scripts/invoke.sh
- tests/javascript/third_parties/marked/test.js
Closes https://github.com/Bearer/bearer/issues/1581
> fix: ensure copy is cleared

- package.json
- scripts/generate/ruleYAMLContent.js
Update remediation message template (following normalization)
Update npm command to be consistent (kebab case not snake)
> fix: update generate-rules script

- .gitignore
Add .idea (Jetbrains) folder to .gitignore
> feat: add .idea to .gitignore

- rules/python/lang/eval_using_user_input.yml
- tests/python/lang/eval_using_user_input/test.js
- tests/python/lang/eval_using_user_input/testdata/main.py
Add Python rule for CWE-95 evil eval injection
> feat(python): eval injection (CWE-95)

- rules/python/django/insecure_cookie.yml
- rules/python/lang/insecure_cookie.yml
- rules/python/shared/django/http_response.yml
- tests/python/django/insecure_cookie/test.js
- tests/python/django/insecure_cookie/testdata/main.py
- tests/python/lang/insecure_cookie/test.js
- tests/python/lang/insecure_cookie/testdata/main.py
Add insecure cookie rule for Python Django
> feat(python): insecure cookie rule (CWE-614)

- rules/python/django/open_redirect.yml
- rules/python/shared/django/user_input.yml
> fix(python): fix typos in redirect and django user input rules

- rules/python/django/file_permissions.yml
- rules/python/lang/file_permissions.yml
- tests/python/django/file_permissions/test.js
- tests/python/django/file_permissions/testdata/main.py
- tests/python/lang/file_permissions/test.js
- tests/python/lang/file_permissions/testdata/main.py
Add Python rules for overly permissive file permissions
> feat(python): file permissions (CWE-276)

- rules/python/django/jwt_weak_encryption.yml
- rules/python/lang/jwt_weak_encryption.yml
- rules/python/lang/weak_encryption_blowfish.yml
- rules/python/lang/weak_encryption_des.yml
- rules/python/lang/weak_encryption_ecb_mode.yml
- rules/python/lang/weak_encryption_rc4.yml
- rules/python/lang/weak_encryption_rsa.yml
- rules/python/lang/weak_random.yml
- rules/python/lang/weak_tls_version.yml
- tests/python/django/jwt_weak_encryption/test.js
- tests/python/django/jwt_weak_encryption/testdata/settings.py
- tests/python/lang/jwt_weak_encryption/test.js
- tests/python/lang/jwt_weak_encryption/testdata/main.py
- tests/python/lang/weak_encryption_blowfish/test.js
- tests/python/lang/weak_encryption_blowfish/testdata/main.py
- tests/python/lang/weak_encryption_des/test.js
- tests/python/lang/weak_encryption_des/testdata/main.py
- tests/python/lang/weak_encryption_ecb_mode/test.js
- tests/python/lang/weak_encryption_ecb_mode/testdata/main.py
- tests/python/lang/weak_encryption_rc4/test.js
- tests/python/lang/weak_encryption_rc4/testdata/main.py
- tests/python/lang/weak_encryption_rsa/test.js
- tests/python/lang/weak_encryption_rsa/testdata/main.py
- tests/python/lang/weak_random/test.js
- tests/python/lang/weak_random/testdata/main.py
- tests/python/lang/weak_tls_version/test.js
- tests/python/lang/weak_tls_version/testdata/main.py
Adds Python rules for CWE-327 Broken/Risky Cryptographic Algorithm.
> feat(python): add cwe-327 broken/risky crypto algorithm rules

- rules/python/lang/nosql_injection.yml
- tests/python/lang/nosql_injection/test.js
- tests/python/lang/nosql_injection/testdata/main.py
Python NoSQLi rule for MongoDB cases
> feat(python): add NoSQLi rule for mongodb (CWE-943)

- rules/python/django/weak_secret_key.yml
- rules/python/lang/weak_hash_adler32.yml
- rules/python/lang/weak_hash_crc32.yml
- rules/python/lang/weak_hash_dss.yml
- rules/python/lang/weak_hash_md5.yml
- rules/python/lang/weak_hash_sha1.yml
- rules/python/lang/weak_password_hash_adler32.yml
- rules/python/lang/weak_password_hash_argon2.yml
- rules/python/lang/weak_password_hash_crc32.yml
- rules/python/lang/weak_password_hash_dss.yml
- tests/python/django/weak_secret_key/test.js
- tests/python/django/weak_secret_key/testdata/main.py
- tests/python/lang/weak_password_hash_adler32/test.js
- tests/python/lang/weak_password_hash_adler32/testdata/main.py
- tests/python/lang/weak_password_hash_argon2/test.js
- tests/python/lang/weak_password_hash_argon2/testdata/main.py
- tests/python/lang/weak_password_hash_crc32/test.js
- tests/python/lang/weak_password_hash_crc32/testdata/main.py
- tests/python/lang/weak_password_hash_dss/test.js
- tests/python/lang/weak_password_hash_dss/testdata/main.py
Adds Python rules for CWE-326 Inadequate Encryption Strength
> feat(python): add cwe-326 inadequate encryption strength rules

- rules/python/lang/deserialization_of_user_input.yml
- tests/python/lang/deserialization_of_user_input/test.js
- tests/python/lang/deserialization_of_user_input/testdata/main.py
Add deserialization rule (CWE-502) for several Python deserialization libraries
> feat(python): deserialization with user input (CWE-502)

- rules/ruby/third_parties/clickhouse.yml
> fix(ruby): ClickHouse typo

- rules/python/third_parties/bugsnag.yml
- tests/python/third_parties/bugsnag/test.js
- tests/python/third_parties/bugsnag/testdata/main.py
> feat(python): add bugsnag third parties rule (CWE-201)

- rules/python/third_parties/clickhouse.yml
- tests/python/third_parties/clickhouse/test.js
- tests/python/third_parties/clickhouse/testdata/main.py
Add Python rule for ClickHouse third party
> feat(python): clickhouse third parties rule (CWE-201)

- rules/python/third_parties/bigquery.yml
- tests/python/third_parties/bigquery/test.js
- tests/python/third_parties/bigquery/testdata/main.py
Add Python third party Google BigQuery rule
> feat(python): add Google BigQuery third party rule (CWE-201)

- rules/python/third_parties/algolia.yml
- tests/python/third_parties/algolia/test.js
- tests/python/third_parties/algolia/testdata/main.py
> feat(python): add algolia third parties rule (CWE-201)

- rules/python/third_parties/new_relic.yml
- tests/python/third_parties/new_relic/test.js
- tests/python/third_parties/new_relic/testdata/main.py
Add Python third party rule for New Relic
> feat(python): add new relic third party rule (CWE-201)

- rules/python/third_parties/scout_apm.yml
- tests/python/third_parties/scout_apm/test.js
- tests/python/third_parties/scout_apm/testdata/main.py
Add Python third party rule for Scout APM
> feat(python): add scout APM third party rule (CWE-201)

- rules/python/third_parties/honeybadger.yml
- tests/python/third_parties/honeybadger/test.js
- tests/python/third_parties/honeybadger/testdata/main.py
Add Python third party rule for HoneyBadger 
> feat(python): add honeybadger third party rule (CWE-201)

- rules/python/third_parties/openai.yml
- tests/python/third_parties/openai/test.js
- tests/python/third_parties/openai/testdata/main.py
Add Python third party rule for Open AI 
> feat(python): add open AI third party rule (CWE-201)

- rules/php/lang/sql_injection.yml
- rules/php/symfony/sql_injection.yml
Add safe list as recommended remediation for SQLi - suggestion from a Discord question
> fix(php): expand recommended remediation for SQLi

- rules/python/django/crlf_injection.yml
> fix(python): typo in code snippet

- rules/go/lang/deserialization_of_user_input.yml
- tests/go/lang/deserialization_of_user_input/testdata/main.go
Catch gob Encoder / Decoder initialized with user input
> fix(golang): deserialization pattern for gob

- rules/javascript/lang/sql_injection.yml
- tests/javascript/lang/sql_injection/test.js
- tests/javascript/lang/sql_injection/testdata/sequelize_fallback_sql_injection.js
Add a fallback for `sequelize` variable
> fix(js): add sequelize fallback

- rules/java/lang/standard_output.yml
- tests/java/lang/ssl_hostname_verifier/testdata/main.java
- tests/java/lang/standard_output/test.js
- tests/java/lang/standard_output/testdata/main.java
Add general CWE-200 rule for information exposure through `System.out.print`
> feat(java): add CWE-200

- rules/java/lang/standard_output.yml
> fix(java): typo in remediation
